configuration:
  projectName: rm-engine-ms-character

server:
  port: 8092

management:
  context-path: /actuator
  security.enabled: false

logging:
  level.org: INFO

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/rmengine
