configuration:
  projectName: rm-engine-web

server:
  port: 8080
  tomcat:
      uri-encoding: UTF-8

management:
  context-path: /actuator
  security.enabled: false

#no cache templates under development phase
spring:
  thymeleaf:
    cache: false

client:
  registerWithEureka: false
  serviceUrl:
    defaultZone: http://localhost:8070/eureka/

zuul:
  routes:
    common:
      path: /api/common/**
      serviceId: rm-engine-ms-common
      stripPrefix: false
    campaign:
      path: /api/campaign/**
      url: http://localhost:8091/
    character:
      path: /api/character/**
      url: http://localhost:8092/
    creation:
      path: /api/creation/**
      url: http://localhost:8093/
    combat:
      path: /api/combat/**
      url: http://localhost:8095/
    maneuver-dynamic:
      path: /api/manouver-static/**
      url: http://localhost:8096/
    maneuver-static:
      path: /api/manouver-dynamic/**
      url: http://localhost:8097/
