configuration:
  projectName: rm-engine-ms-common

spring:
  application:
    name: rm-engine-ms-common
  data:
    mongodb:
      uri: mongodb://localhost:27017/rmengine

server:
  port: 8090

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  context-path: /admin
  security:
    enabled: false

logging:
  level.org: INFO
