configuration:
  projectName: rm-engine-web

spring:
  application:
    name: rm-engine-web
  thymeleaf:
    #no cache templates under development phase
    cache: false

zuul:
  prefix: /api
  routes:
    # Error: eureka discovery dont resove server list (see issues):
    #rm-engine-ms-common: /common/**
    common:
      path: /common/**
      url: http://localhost:8090/
    campaign:
      path: /campaign/**
      url: http://localhost:8091/
    character:
      path: /character/**
      serviceId: rm-engine-ms-character
    creation:
      path: /creation/**
      url: http://localhost:8093/
    combat:
      path: /combat/**
      url: http://localhost:8095/
    maneuver-dynamic:
      path: /manouver-static/**
      url: http://localhost:8096/
    maneuver-static:
      path: /manouver-dynamic/**
      url: http://localhost:8097/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

#ribbon:
#  eureka:
#    enabled: true

#ribbon:
#  eureka:
#   enabled: true
#    ReadTimeout: 20000
#    ConnectTimeout: 20000

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

management:
  context-path: /admin
  security.enabled: false

logging:
  level.org: INFO
