configuration:
  projectName: rm-engine-ms-campaign

server:
  port: 8091

management:
  context-path: /admin
  security.enabled: false

logging:
  level.org: INFO

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/rmengine
