configuration:
  projectName: rm-engine-ms-combat

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/rmengine

server:
  port: 8095

management:
  context-path: /admin
  security:
    enabled: false

logging:
  level.org: INFO
