configuration:
  projectName: rm-engine-ms-common

spring:
  application:
    name: rm-engine-ms-common
  data:
    mongodb:
      uri: mongodb://localhost:27017/rmengine

server:
  port: 8090

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: http://localhost:8070/eureka/
  client:
    registryFetchIntervalSeconds: 5

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka/

management:
  context-path: /actuator
  security:
    enabled: false

logging:
  level.org: INFO
