configuration:
  projectName: rm-engine-ms-character

server:
  port: 8092

management:
  context-path: /actuator
  security.enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

logging:
  level.org: INFO

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/rmengine
