configuration:
  projectName: rm-engine-ms-character

spring:
  application:
    name: rm-engine-ms-character
  data:
    mongodb:
      uri: mongodb://localhost:27017/rmengine

server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  context-path: /actuator
  security:
    enabled: false

logging:
  level.org: INFO
